storage:
  tsdb:
    out_of_order_time_window: 30m
    retention:
      time: 7d
      size: 1GB

otlp:
  # Recommended attributes to be promoted to labels.
  promote_resource_attributes:
    - service.instance.id
    - service.name
    - service.namespace
    - service.version
    - cloud.availability_zone
    - cloud.region
    - container.name
    - deployment.environment
    - deployment.environment.name

# remote_write:
#   - url: "http://localhost:9090/api/v1/otlp/v1/metrics"