name: Setup Ansible
description: Shared steps for Ansible installation

inputs:
  ssh_private_key:
    description: SSH Private Key
    required: true
  ssh_host:
    description: SSH Host
    required: true
  ssh_user:
    description: SSH User
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.13'

    - name: Install Ansible
      run: |
        python -m pip install --upgrade pip
        pip install ansible
      shell: bash

    - name: Setup SSH Private Key
      env:
        SSH_PRIVATE_KEY: ${{ inputs.ssh_private_key }}
        SSH_HOST: ${{ inputs.ssh_host }}
        SSH_USER: ${{ inputs.ssh_user }}
      run: |
        mkdir -p ~/.ssh
        echo "${SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${SSH_HOST} >> ~/.ssh/known_hosts
      shell: bash

    - name: Test SSH Connection
      run: ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ${SSH_USER}@${SSH_HOST} "echo Connected!"
      shell: bash