apiVersion: 1

datasources:
  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    jsonData:
      # timeout: 60
      # maxLines: 1000
      serviceMap:
        datasourceUid: 'Prometheus'
      nodeGraph:
        enabled: true
