name: CI

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code source
        uses: actions/checkout@v5
      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${{ vars.FRONTEND_PNPM_VERSION}}
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ vars.BACKEND_NODE_VERSION}}
          cache: "pnpm"
      - name: Install dependencies
        run: make install-frontend-dependences
      - name: Build
        run: make build-frontend
      - name: Test
        run: make test-frontend