name: CI

on: 
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app: [
          {
            name: 'frontend', 
            dir: 'new-frontend'
          }
        ]
    # defaults:
    #   run:
    #     working-directory:  ${{ github.workspace }}/${{ matrix.app.dir }}
    steps:
      - name: Checkout Code Source
        uses: actions/checkout@v5

      - name: Set Env Variables
        run: |
          case "${{ matrix.app.name }} in 
            frontend)
              echo "PNPM_VERSION=${{ vars.FRONTEND_PNPM_VERSION }}" >> GITHUB_ENV
              echo "NODE_VERSION=${{ vars.FRONTEND_NODE_VERSION }}" >> GITHUB_ENV
              ;;
            backend)
              echo "PNPM_VERSION=${{ vars.BACKEND_PNPM_VERSION }}" >> GITHUB_ENV
              echo "NODE_VERSION=${{ vars.BACKEND_NODE_VERSION }}" >> GITHUB_ENV
              ;;
          esac

      - name: Install Pnpm
        uses: pnpm/action-setup@v4
        with:
          version: ${PNPM_VERSION}

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${NODE_VERSION}
          cache: "pnpm"

      - name: Install Dependencies
        run: make ci-install-${{ matrix.app.name }}-dependences
      - name: Build
        run: make ci-build-${{ matrix.app.name }}
      - name: Lint
        run: make ci-lint-${{ matrix.app.name }}
      - name: Test
        run: make ci-test-${{ matrix.app.name }}