---
name: Import Existing Infrastructure

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Environment (prod/dev)"
        required: true
        default: 'prod'
        type: choice
        options:
          - prod
          - dev

jobs:
  import-infra:
    name: Import Current GCP Infrastructure
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    defaults:
      run:
        working-directory: ./infra/automation/terraform/01_infra
    steps:
      - name: Checkout Code Source
        uses: actions/checkout@v5

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.14.3"

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v3
        with:
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}

      - name: Select Project
        run: gcloud config set project ${{ vars.GCP_PROJECT_ID }}

      - name: Init Terraform Directory / Download Providers [infra]
        run: |
          terraform init \
          -backend-config="bucket=${{ vars.BUCKET_NAME }}" \
          -input=false

      # Terraform workspaces for dev/prod envinronments
      - name: Select Workspace
        run: terraform workspace select -or-create=true ${{ github.event.inputs.environment }}

      - name: Check Format & Validate Terraform files [infra]
        run: | 
          terraform fmt -check
          terraform validate

      - name: Import Existing Infrastructure
        env:
          TF_LOG: DEBUG
          TF_VAR_ssh_user: ${{ vars.SSH_USER }}
          TF_VAR_ssh_public_key: ${{ vars.SSH_PUBLIC_KEY }}
          TF_VAR_region: ${{ vars.BUCKET_LOCATION }}
          TF_VAR_project: ${{ vars.GCP_PROJECT_ID }}
          TF_VAR_bucket_name: ${{ vars.BUCKET_NAME }}
        run: |
          # terraform import -input=false google_storage_bucket.tf_backend ${{ vars.BUCKET_NAME }}
          terraform import -input=false google_compute_disk.persistent vm-disk-prod-97532680
          terraform import -input=false google_compute_network.vpc_network vpc-network-prod-97532680
          terraform import -input=false google_compute_firewall.https projects/portfolio-prod-97532680/global/firewalls/https-access
          terraform import -input=false google_compute_firewall.default projects/portfolio-prod-97532680/global/firewalls/http-access
          terraform import -input=false google_compute_image.ubuntu_with_disk projects/portfolio-prod-97532680/global/images/ubuntu-with-disk-image-prod-97532680
          terraform import -input=false google_compute_firewall.ssh projects/portfolio-prod-97532680/global/firewalls/ssh