---
name: Deploy To Server

on:
  workflow_dispatch:
    inputs:
        sytem_version:
          description: "The version of the system to be deployed"
          type: string
          required: true
          default: '0.1.0'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code Source
        uses: actions/checkout@v5

      - name: Setup Ansible
        uses: ./.github/actions/setup-ansible
        with:
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh_host: ${{ vars.SSH_HOST }}
          ssh_user: ${{ vars.SSH_USER }}
        
      - name: Deploy via Ansible
        run: |
          ansible-playbook ${{ github.workspace }}/infra/automation/ansible/playbooks/playbook_deploy.yaml \
          -i ${{ github.workspace }}/infra/automation/ansible/inventories/inventory.yaml \
          -u ${{ vars.SSH_USER }} \
          -e "system_version=${{ github.event.inputs.sytem_version }}" \  
          -e "cf_dns_api_token=${{ secrets.CF_DNS_API_TOKEN }}" \
          -e "frontend_node_version=${{ vars.FRONTEND_NODE_VERSION }}" \
          -e "frontend_pnpm_version=${{ vars.FRONTEND_PNPM_VERSION }}" \
          -e "backend_pnpm_version=${{ vars.BACKEND_PNPM_VERSION }}" \
          -e "backend_node_version=${{ vars.BACKEND_NODE_VERSION }}" \
          -e "api_url=${{ vars.API_URL }}" \
          -e "backend_base_url=${{ vars.BACKEND_BASE_URL }}" \
          -e "database_client=${{ vars.DATABASE_CLIENT }}" \
          -e "database_name=${{ vars.DATABASE_NAME }}" \
          -e "database_username=${{ vars.DATABASE_USERNAME }}" \
          -e "database_password=${{ secrets.DATABASE_PASSWORD }}" \
          -e "database_port=${{ vars.DATABASE_PORT }}" \
          -e "jwt_token=${{ secrets.JWT_SECRET }}" \
          -e "app_keys=${{ secrets.APP_KEYS }}" \
          -e "admin_jwt_secret=${{ secrets.ADMIN_JWT_SECRET }}" \
          -e "encryption_key=${{ secrets.ENCRYPTION_KEY }}" \
          -e "api_token_salt=${{ secrets.API_TOKEN_SALT }}" \
          -e "transfer_token_salt=${{ secrets.TRANSFER_TOKEN_SALT }}" \
          -e "database_filename=${{ vars.DATABASE_FILENAME }}" \
          -e "strapi_telemetry_disabled=${{ vars.STRAPI_TELEMETRY_DISABLED }}" \
          -e "node_env=${{ vars.NODE_ENV }}" \
          -e "admin_auth_credentials=${{ secrets.ADMIN_AUTH_CREDENTIALS }}" \
          -e "pimary_domain=${{ vars.PRIMARY_DOMAIN }}" \
          -e "site_name=${{ vars.SITE_NAME }}" \
          -e "repo_namespace=${{ vars.REPO_NAMESPACE }}" \
          -e "dns_email=${{ vars.DNS_EMAIL }}" \
          -e "certificate_resolver_name=${{ vars.CERTIFICATE_RESOLVER_NAME }}" \
          -e "ca_server=${{ vars.CA_SERVER }}" \
          -e "ansible_host=${{ vars.SSH_HOST }}"